<?php

defined('BASEPATH') or exit('No direct script access allowed');

class EmailTest extends CI_Controller
{
    private $group_id = 0;
    private $user_id = 0;
    private $group_type = "";

    public function __construct()
    {
        parent::__construct();

        $this->load->model('Ion_auth_model');
        $this->load->model('Tracking_model');
        $this->load->helper(array('form', 'url', 'file', 'activity_helper', 'dashboard_functions_helper', 'ec_helper'));

        // track_user_activity(); //Track user activity function which logs user track actions.

        $this->user_id = $this->ion_auth->user()->row()->id;
        $group_row = $this->ion_auth->get_users_groups()->row();
        $this->group_type = $group_row->group_type;
        $this->group_id = $group_row->id;
    }

    public function SendEmail()
    {
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        // $ch = curl_init();
        
        // curl_setopt($ch, CURLOPT_URL, 'https://api.mailgun.net/v3/sandbox90ed3a307fbf4a5498b2c3ea1bb533e0.mailgun.org/messages');
        // curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        // curl_setopt($ch, CURLOPT_POST, 1);
        // $post = array(
        //     'from' => 'vishal@dreamzdigitalsolutions.com',
        //     'to' => 'vishal@dreamzdigitalsolutions.com',
        //     'subject' => 'Email',
        //     'text' => '<h1>Hello</h1><br>,<p> How are you</p>',
        //     'Content-Type' => 'text/html'
        // );
        // curl_setopt($ch, CURLOPT_POSTFIELDS, $post);
        // curl_setopt($ch, CURLOPT_USERPWD, 'api' . ':' . '31c8539797bd0e17a10790ae47b15493-31eedc68-5993a66e');
        // curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

        // $result = curl_exec($ch);
        // if (curl_errno($ch)) {
        //     echo 'Error:' . curl_error($ch);
        // }
        // curl_close($ch);
        // echo "<pre>";
        // print_r(json_decode($result));
        // die;

        require_once(APPPATH . 'third_party/phpmailer/src/PHPMailer.php');
        require_once(APPPATH . 'third_party/phpmailer/src/SMTP.php');
        require_once(APPPATH . 'third_party/phpmailer/src/Exception.php');
        $mail = new PHPMailer\PHPMailer\PHPMailer();


        $mail->isSMTP();
        $mail->Host     = 'smtp.mailgun.org';
        $mail->SMTPAuth = true;
        $mail->Username = 'postmaster@sandbox90ed3a307fbf4a5498b2c3ea1bb533e0.mailgun.org';
        $mail->Password = '181d15e29823b36c5a40fa061031dac0-31eedc68-fa846aaf';
        // $mail->SMTPSecure = 'ssl';
        $mail->Port     = 587;

        $mail->setFrom('vishal@dreamzdigitalsolutions.com', 'Demo');
        $mail->addReplyTo('vishal@dreamzdigitalsolutions.com', 'Demo');

        // Add a recipient
        $mail->addAddress('vishal@dreamzdigitalsolutions.com');

        // Add cc or bcc 
        // $mail->addCC('cc@example.com');
        // $mail->addBCC('bcc@example.com');

        // Email subject
        $mail->Subject = 'Send Email via SMTP using PHPMailer in CodeIgniter';

        // Set email format to HTML
        $mail->isHTML(true);

        // Email body content
        $mailContent = "<h1>Send HTML Email using SMTP in CodeIgniter</h1>
            <p>This is a test email sending using SMTP mail server with PHPMailer.</p>";
        $mail->Body = $mailContent;

        // Send email
        if(!$mail->send()){
            echo 'Message could not be sent.';
            echo 'Mailer Error: ' . $mail->ErrorInfo;
        }else{
            echo 'Message has been sent';
        }
        exit;
    }
}
